name: Check components version

on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run version check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_version.py --ci-check

      - name: Parse version_diff.json
        id: parse_version_diff
        run: |
          cat version_diff.json
          echo "::set-output name=version_diff::$(cat version_diff.json)"

      - name: Trigger subsequent action for each component
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version_diff=$(cat version_diff.json)
          for row in $(echo "${version_diff}" | jq -r 'to_entries[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            
            component=$(_jq '.key')
            current_version=$(_jq '.value.current_version')
            latest_version=$(_jq '.value.latest_version')
            component_release=$(_jq '.value.component_release')

            echo "Triggering update for $component from $current_version to $latest_version"
            
            gh workflow run dependency-pull-request.yml \
              --ref main \
              -f component=$component \
              -f current_version=$current_version \
              -f latest_version=$latest_version \
              -f component_release="$component_release"
          done
