name: Update Component Versions

on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Update Version Script
        run: |
          python update_version.py --loglevel DEBUG

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dependency-checksum
          title: 'Update dependency checksum to the latest version'
          body: 'This PR updates the dependency checksum to the latest version.'
          labels: 'dependencies'
